# Generated by Django 5.1.3 on 2024-11-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема сообщения')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('status', models.CharField(choices=[('NEW', 'Новое'), ('VIEWED', 'Просмотрено'), ('REACTED', 'Отреагировано')], default='NEW', max_length=100, verbose_name='Статус')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сообщение о проблеме',
                'verbose_name_plural': 'Сообщения о проблемах',
            },
        ),
    ]
