# Generated by Django 5.1.3 on 2024-11-19 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('gender', models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=6, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, verbose_name='Email адрес')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('series', models.PositiveIntegerField(blank=True, verbose_name='Серия')),
                ('number', models.PositiveIntegerField(blank=True, verbose_name='Номер')),
                ('issued', models.CharField(blank=True, max_length=255, verbose_name='Выдан')),
                ('departament_code', models.PositiveIntegerField(blank=True, verbose_name='Код подразделения')),
                ('date_issue', models.DateField(blank=True, verbose_name='Дата выдачи')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь портала',
                'verbose_name_plural': 'Пользователи портала',
            },
        ),
    ]
